server:
  port: 8080

spring:
  cloud:
    config:
      enabled: false

  application:
    name: api-gateway

services:
  auth:
    uri: ${SERVICES_AUTH_URI:http://localhost:8082}
    public-paths: ${SERVICES_AUTH_PUBLIC_PATHS:/api/v1/login}
    private-paths: ${SERVICES_AUTH_PRIVATE_PATHS:/api/v1/usuarios,/api/v1/validar, /api/v1/salario}
  solicitudes:
    uri: ${SERVICES_SOLICITUDES_URI:http://localhost:8081}
    paths: ${SERVICES_SOLICITUDES_PATHS:/api/v1/solicitud}
  reportes:
    uri: ${SERVICES_REPORTES_URI:http://localhost:8083}
    private-paths: ${SERVICES_REPORTES_PRIVATE_PATHS:/api/v1/reportes/total, /api/v1/reportes/monto}

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-1234567890abcdef}
